name: PerfFlowAspect CI
on: [ push, pull_request ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout PerfFlowAspect repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup Build Env
        run: |
          sudo apt-get update
          sudo apt install clang llvm-dev libjansson-dev libssl-dev bison flex make cmake

      - name: Build Parser
        run: |
          cd src/c/parser
          make VERBOSE=1

      - name: Build Runtime
        run: |
          cd src/c/runtime
          make VERBOSE=1

      - name: Configure Weaver with CMake
        run: |
          cd src/c/weaver
          mkdir build
          cd build
          LLVM_DIR=/usr/lib/llvm-6.0/lib/cmake/llvm cmake ..

      - name: Build Weaver
        run: |
          cd src/c/weaver/build
          make VERBOSE=1

      - name: Run C Smoke Tests
        run: |
          cd src/c/test
          make VERBOSE=1
          sh t0001-cbinding-basic.t
